config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/catalogue", to: "pages#index", as:"catalogue"
  get "instrument/:id", to: "pages#show",as:"instrument"
  get "/products/:category", to: "pages#category",as:"cateinstrument"
  get "/Abouts-us", to: "pages#Aboutus", as:"about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/booking", to: "pages#booking", as: "booking"
  get "/dashboard", to: "pages#dashboard", as: "dashboard"
  get '/rev', to: 'pages#new_review', as: 'review'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :instrument
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :instrument
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :instrument, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @instrument = Instrument.all
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end

  def find
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  # before_action :authenticate_user!, only: :home
  def index
    @instruments = Instrument.all
  end

    def show
      @ins = Instrument.find(params[:id])
      @reviews = Review.where(instrument_id: @ins.id)
    end

  def new
  end

  def create
  end

  def find
  end

  def destroy
  end
  def category
    @instru = Instrument.where(category: params[:category])
  end
  def instrument
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home
   before_action :authenticate_user!

  def home
  end

  def index
    @instruments = Instrument.all
  end


  def show
    @ins = Instrument.find(params[:id])
    @user_id = current_user.id
  #   user = User.find(@user_id)
  #   @email = user.email

  #   # Check if the user has booked this instrument
    @booking = Booking.find_by(user_id: @user_id, instrument_id: @ins.id)
    @reviews = Review.where(instrument_id: @ins.id).order(rating: :desc).limit(2)
  #     # User has booked the instrument, fetch reviews
  #   else
  #     # User has not booked the instrument, do something (redirect, show a message, etc.)
  #     flash[:alert] = "You must book this instrument to write a review and rate it."
  #     redirect_to root_path # Redirect to home or another appropriate path
  #   end
  end
  def category
    @instru = Instrument.where(category: params[:category])
  end
  def instrument
  end

  def booking
    @user = User.find(params[:user_id])
    @starting_date = Date.parse(params[:starting_date])
    @ending_date = Date.parse(params[:ending_date])
    @input_value = params[:input_value]
    @instrument = Instrument.find(params[:instrument_id])
    @number_of_days = (@ending_date - @starting_date).to_i


    @booking = Booking.new(
      user_id: @user.id,
      starting_date: @starting_date,
      ending_date: @ending_date,
      instrument_id: @instrument.id,
    )
    if @booking.save
      redirect_to dashboard_path, notice: 'Booking was successfully created.'
    else

      render :booking
    end


  end

  def dashboard
    @user_dashboard_id = current_user.id
    @user_dashboard = User.find(@user_dashboard_id)
    @bookings = Booking.where(user_id: @user_dashboard_id)
    @reviews = Review.where(user_id: @user_dashboard_id)
  end

  def new_review
    @a = params[:comment]
    @rate = params[:rating]
    @ins_idd = params[:ins_id]
    @usr = params[:usr_id]
    @review = Review.new(
      comment: @a,
      rating: @rate,
      instrument_id: @ins_idd,
      user_id: @usr
    )
    if @review.save
      redirect_to dashboard_path, notice: 'review was successfully created.'
    else
      render :review
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/instruments/cate.html.erb
<% @instru.each do |i| %>
  <div class="instrument-box">
   <a href="<%= instrument_path(i) %>">
    <strong>Name:</strong> <%= i.name %><br>
    <strong>Category:</strong> <%= i.category %><br>
    <!-- Add more instrument details as needed -->
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MelodyMarket</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/Aboutus.html.erb
<div class="container-aboutus">
    <h1>About Us</h1>

    <p>Welcome to <strong>Melody Market</strong> – Your Ultimate Destination for Musical Instrument Rentals!</p>

    <p>At Melody Market, we're passionate about music and believe that everyone should have the opportunity to express their creativity through playing musical instruments. That's why we've created a platform where music enthusiasts and budding musicians can easily rent high-quality instruments without breaking the bank.</p>

    <h3>Who We Are</h3>
    <p>We are a dedicated team of music lovers, consisting of musicians, tech enthusiasts, and entrepreneurs, brought together by our shared love for melodies and rhythms. Our mission is to make the joy of music accessible to everyone, regardless of their skill level or background.</p>

    <h3>What We Offer</h3>
    <ul>
        <li><strong>Wide Variety of Instruments:</strong> From classic guitars and pianos to exotic world instruments, we offer a diverse range of musical instruments for rent. Whether you're a beginner experimenting with your first chords or a seasoned musician looking for a specific sound, you'll find what you need here.</li>
        <li><strong>Quality and Safety:</strong> We understand the importance of playing on a reliable instrument. That's why we meticulously maintain our inventory, ensuring that every instrument you rent is in top-notch condition. Your safety and satisfaction are our top priorities.</li>
        <li><strong>Affordable Options:</strong> Music shouldn't be a luxury. Our affordable rental plans make it easy for everyone to explore the world of music without a hefty price tag. Rent instruments for a day, a week, or even months – we've got flexible plans to suit your needs.</li>
        <li><strong>Exceptional Customer Support:</strong> Have a question or need assistance? Our dedicated customer support team is always here to help. Whether you need guidance on choosing the right instrument or have inquiries about your rental, we're just a message away.</li>
    </ul>

    <h3>Join Us in the Melodic Journey</h3>
    <p>Whether you're a student, a hobbyist, or a professional musician, Melody Market invites you to embark on a melodic journey with us. Discover new sounds, refine your skills, and let the music flow.</p>

    <p>Thank you for being a part of our musical community!</p>
</div>

app/views/pages/booking.html.erb
<h1>BOOKING</h1>

<hr>

<div>
  <h2>
    <%= @user.email %>

    <p>
      Books >>>>> <%= @instrument.name %>
    </p>
    <p>
      for >>>>> <%= @number_of_days %> days
    </p>
    <p>
      total >>>>> <%= @number_of_days * @instrument.price %>
      <p> for <%= @instrument.price %> per day</p>
    </p>
  </h2>

  <%= form_tag(booking_path, method: :post) do %>
    <%= hidden_field_tag :user_id, @user.id %>
    <%= hidden_field_tag :instrument_id, @instrument.id %>
    <%= hidden_field_tag :starting_date, @starting_date %>
    <%= hidden_field_tag :ending_date, @ending_date %>

    <%= check_box_tag :confirmed, true %>
    <%= label_tag :confirmed, 'I confirm my booking details' %>

    <%= submit_tag 'Confirm Booking' %>
  <% end %>
</div>

<hr>

app/views/pages/category.html.erb
<% @instru.each do |i| %>
  <div class="instrument-box">
   <a href="<%= instrument_path(i) %>">
    <strong>Name:</strong> <%= i.name %><br>
    <strong>Category:</strong> <%= i.category %><br>
    <!-- Add more instrument details as needed -->
  </div>
<% end %>

app/views/pages/dashboard.html.erb
<div class="home_booking">
<h1>My Bookings</h1>
<ul>
  <% @bookings.each do |booking| %>
  <h2>
    <li>
      Booking ID: <%= booking.id %>,
      Instrument Name: <%= booking.instrument.name %>,
      Starting Date: <%= booking.starting_date %>,
      Ending Date: <%= booking.ending_date %>
    </li>
    </h2>
  <% end %>
</ul>

<h1>My Reviews</h1>
<ul>
  <% @reviews.each do |review| %>
  <h2>
    <li>Review ID: <%= review.id %>, Rating: <%= review.rating %>, Comment: <%= review.comment %></li>
    </h2>
  <% end %>
</ul>
</div>

app/views/pages/home.html.erb
</div><div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= asset_path('Instruments/Saxophone/jens-thekkeveettil-dBWvUqBoOU8-unsplash(1).jpg') %>'); margin-top:-4rem;">
  <div class="container">
    <h1>Rent your dream <br> instrument. </h1>
    <a class="banner-button" href="/catalogue">Choose an instrument </a>
  </div>
</div>

<%# // Popular instruments %>

<div class="">
  <div class=“instruments-categories”>
    <h2 class=“secondary-title”> Popular instruments </h2>
  </div>
  <div class="parent">
    <div class="child">
      <button class="button-rel">Piano</button> <%= image_tag 'Instruments/Piano/Piano1.jpg', class: "child-half" %>
  <div class="child">
    <button class="button-rel">Guitar</button> <%= image_tag 'Instruments/Guitar/thomas-kelley-2ZWCDBuw1B8-unsplash.jpg', class: "child-half" %>
    </div>
  </div>
    <div class="child">
      <button class="button-rel">Saxophone</button> <%= image_tag 'Instruments/Saxophone/benjamin-lehman-0h2F-Ib2Zdo-unsplash.jpg', class: "child-full" %>
    </div>
    <div class="child">
      <button class="button-rel">Batteries</button> <%= image_tag 'Instruments/Batteries/matthijs-smit-bRG2C0FAQEY-unsplash.jpg', class: "child-half" %>
  <div class="child">
      <button class="button-rel">Violon</button> <%= image_tag 'Instruments/Violon/baher-khairy-uqKyeMaaAOQ-unsplash.jpg', class: "child-half" %>
    </div>
  </div>

  </div>
</div>

<%# // Instruments categories %>



<%# // Top rated instruments %>



<%#
  <div class="img-container">
    <div class="row">
      <div class="column">
        <img src="https://www.w3schools.com/w3images/wedding.jpg" style="width:100%">
        <img src="https://www.w3schools.com/w3images/rocks.jpg" style="width:100%">
      </div>
      <div class="column">
        <img src="https://www.w3schools.com/w3images/underwater.jpg" style="width:100%">
        <img src="https://www.w3schools.com/w3images/ocean.jpg" style="width:100%">
        <img src="https://www.w3schools.com/w3images/wedding.jpg" style="width:100%">
        <img src="https://www.w3schools.com/w3images/mountainskies.jpg" style="width:100%">
      </div>
      <div class="column">
        <img src="https://www.w3schools.com/w3images/wedding.jpg" style="width:100%">
        <img src="https://www.w3schools.com/w3images/rocks.jpg" style="width:100%">
      </div>
      <div class="column">
        <img src="https://www.w3schools.com/w3images/underwater.jpg" style="width:100%">
        <img src="https://www.w3schools.com/w3images/ocean.jpg" style="width:100%">
        <img src="https://www.w3schools.com/w3images/wedding.jpg" style="width:100%">
        <img src="https://www.w3schools.com/w3images/mountainskies.jpg" style="width:100%">
      </div>
    </div>
  </div>
</div>
 %>



<%
=begin%>
 <%= link_to "string", cateinstrument_path("String Instruments") %>
<div class="instrument-section">
  <div class="instrument-content">
    <img class="instrument-image" src="<%= asset_path('Instruments/Guitar/brent-ninaber-C8gib_msapY-unsplash.jpg') %>" alt="String Instruments Image">
    <div class="instrument-text"><%= "String Instruments" %></div>
  </div>
</div>

<div class="popular-instruments">
  <h2 class="secondary-title"> Popular instruments </h2>
    <div class="container-popular-instrument toto">
      <div class="main-photo"> <%= image_tag "Instruments/Piano/Piano1.jpg"%></div>
      <div class="small1 foto"> <%= image_tag "Instruments/Piano/Piano1.jpg"%></div>
      <div class="small2 foto"> <%= image_tag "Instruments/Piano/Piano1.jpg"%></div>
      <div class="small3 foto"> <%= image_tag "Instruments/Piano/Piano1.jpg"%></div>
      <div class="small4 foto"> <%= image_tag "Instruments/Piano/Piano1.jpg"%></div>
    </div>
</div>



<%
=begin%>
 middle content
<%
=end%>

app/views/pages/index.html.erb
<h3>Explore instruments</h3>

<div class="catalogue-links-container">
  <div class="single-link">
    <%= link_to "Piano", "#", class: "btn btn-outline-secondary" %>
  </div>
  <div class="single-link">
    <%= link_to "Guitar", "#", class: "btn btn-outline-secondary" %>
  </div>
  <div class="single-link">
    <%= link_to "Battery", "#", class: "btn btn-outline-secondary" %>
  </div>
  <div class="single-link">
    <%= link_to "Saxophone", "#", class: "btn btn-outline-secondary" %>
  </div>
  <div class="single-link">
    <%= link_to "Violin", "#", class: "btn btn-outline-secondary" %>
  </div>
</div>

<div class="string_card">
<h2>String Instruments</h2>
  <% @instruments.where(category:"String Instruments").each do |i| %>
  <%= render "shared/instrument_card", i: i %>
<% end %>
</div>



<div class="wind_card">
<h2>Wind Instruments</h2>
  <% @instruments.where(category:"Wind Instruments").each do |i| %>
  <%= render "shared/instrument_card1", i: i %>
<% end %>
</div>

<div class="percussion_card">
<h2>Percussion Instruments</h2>
  <% @instruments.where(category:"Percussion Instruments").each do |i| %>
  <%= render "shared/instrument_card2", i: i %>
<% end %>
</div>

<div class="keyboard_card">
<h2>Keyboard Instruments</h2>
  <% @instruments.where(category:"Keyboard Instruments").each do |i| %>
  <%= render "shared/instrument_card3", i: i %>
<% end %>
</div>

app/views/pages/instrument.html.erb
<h1>hi</h1>

app/views/pages/new_review.html.erb
<h1><%= @a %></h1>

app/views/pages/show.html.erb
<div class="show-home">
    <div class="ins">

      <h2><%= @ins.name %></h2>


      <h2>Price: <%= @ins.price %> /day</h2>

      <h2> location: <%=@ins.location%></h2>

      <h2 id="description">
      Description

      <p>
        Amazing Instrument!!!!!!!
      </p>

  </div>
      <hr>

    <hr>



  <div class="review">
    <h2>Reviews for <%= @ins.name %></h2>


    <% @reviews.each do |review| %>
      <%= review.comment %>

      <p>Rating: <%= review.rating %></p>
      <h2 id="person">from: <%= review.user.email %></h2>
    <% end %>
  </div>

      <hr>
          <hr>



  <div class="book">
      <%= form_tag("/booking", method: "get") do %>
        <%= hidden_field_tag(:user_id, current_user.id) %>
        <%= hidden_field_tag(:instrument_id, @ins.id) %>
        <%= date_field_tag(:starting_date, params[:starting_date], placeholder: "Starting Date",style:"width:300px;height:30px;") %>
        <p>
        </p>
        <%= date_field_tag(:ending_date, params[:ending_date], placeholder: "Ending Date",style:"width:300px;height:30px;") %>
        <p>
        </p>
        <%= submit_tag("Submit") %>
      <% end %>
    </h2>
  </div>

    <hr>


<% if @booking.present?%>
<hr>
<div class="rev">
  <%= form_tag("/rev", method: "get") do %>
    <%= text_field_tag(:comment, params[:comment], placeholder:"comment") %>
    <%= text_field_tag(:rating , params[:rating], placeholder: "rating[1 to 5]") %>
    <%= hidden_field_tag(:ins_id, @ins.id)%>
    <%= hidden_field_tag(:usr_id , @current_user.id)%>
    <%= submit_tag("Submit") %>
  <% end %>
  <% end %>

</div>
<hr>

  <%
=begin%>
 <div class="class">
    <h2>Other Available Instruments</h2>
  </div>
</div>
<%
=end%>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-white">

  <!-- Grid container -->
  <div class="container p-4">

    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>

    <!-- Copyright -->
    <div class="text-center p-2">
      © 2023 Melody Market
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

app/views/shared/_instrument_card.html.erb
<div class="card-product">
        <a href="<%= instrument_path(i) %>">
          <%= image_tag 'Instruments/Guitar/brahan-milla-VqQ26SBuL8U-unsplash.jpg'%>
          <div class="card-product-infos">
            <h2 class="string-instruments"><%= i.name %></h2>

            <p>per/<%= i.price %>day</p>
          </div>
        </a>
      </div>

app/views/shared/_instrument_card1.html.erb
<div class="card-product">
        <a href="<%= instrument_path(i) %>">
          <%= image_tag 'Instruments/Saxophone/konstantin-aal-Otx5FHbr3OE-unsplash.jpg'%>
          <div class="card-product-infos">
            <h2 class="string-instruments"><%= i.name %></h2>

            <p>per/<%= i.price %>day</p>
          </div>
        </a>
      </div>

app/views/shared/_instrument_card2.html.erb
<div class="card-product">
        <a href="<%= instrument_path(i) %>">
          <%= image_tag 'Instruments/Batteries/aliane-schwartzhaupt-QdmUva6qBTk-unsplash.jpg'%>
          <div class="card-product-infos">
            <h2 class="string-instruments"><%= i.name %></h2>

            <p>per/<%= i.price %>day</p>
          </div>
        </a>
      </div>

app/views/shared/_instrument_card3.html.erb
<div class="card-product">
        <a href="<%= instrument_path(i) %>">
          <%= image_tag 'Instruments/Piano/geert-pieters-8QrPJ3Kfie4-unsplash.jpg'%>
          <div class="card-product-infos">
            <h2 class="string-instruments"><%= i.name %></h2>

            <p>per/<%= i.price %>day</p>
          </div>
        </a>
      </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon nav-bar-replace">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("Logo.png") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Catalogue",catalogue_path, class: "nav-link" %>
          </li>
          <li class="nav-item" id="mes">
            <%= link_to "About us", about_path, class: "nav-link" %>
          </li>
           <li class="nav-item" id="mes">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://static.wikia.nocookie.net/bttf/images/2/2c/Michael_Jackson.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%
=begin%>
 <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
<%
=end%>
              <%= link_to "Log out", destroy_user_session_path , class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>